// packages/react/src/gridstack/GridstackContainer.jsx
import React, { useEffect, useState, useRef, useImperativeHandle } from "react";
import "@declarative-gridstack/core/dist/gridstack-extra.min.css";
import "@declarative-gridstack/core/dist/gridstack.min.css";
import { GridStack } from "@declarative-gridstack/core";
import getUpdatedLayout from "./utils/getUpdatedLayout";
import {
  MasterGridContext,
  UpdateLayoutContext,
  RemoveItemFromModelContext,
  AddItemToModelContext,
  ItemStoreContext,
} from "./contexts";
import getGridOptions from "./utils/getGridOptions.js";
import cloneDeep from "lodash/cloneDeep";

const GridstackLayout = React.forwardRef((props, ref) => {
  const grid = useRef();
  const gridContainerElement = useRef();
  const masterGridOptions = getGridOptions(props);
  const isGridDestroyed = useRef();

  const updateItem = (id, dimension) => {
    const item = getItemElementUsingId(id);
    grid.current.update(item, dimension);
  };

  useImperativeHandle(
    ref,
    () => {
      return {
        remove: removeItem,
        updateItem: updateItem,
      };
    },
    // eslint-disable-next-line
    []
  );

  const getItemElementUsingId = (id) => {
    return gridContainerElement.current.querySelector(
      `.grid-stack-item[gs-id="${id}"]`
    );
  };

  const removeItem = (itemId) => {
    const itemElem = getItemElementUsingId(itemId);
    grid.current.removeWidget(itemElem, false); // RemoveDOM = false, don't remove DOM.
  };

  const itemsHash = useRef(); // Make a hash of props.items, always keep itemsHash in sync with props.items

  useEffect(() => {
    const { items } = props;
    itemsHash.current = items.reduce((hash, item) => {
      const { id } = item;
      hash[id] = item;
      return hash;
    }, {});
  }, [props.items.length]);

  const removeItemFromModel = (itemId) => {
    setLayout((prevlayout) => {
      const removeItemById = (id, prevLayout) => {
        return prevLayout.filter((item) => {
          if (item.id === id) {
            return false; // Skip the item to remove it
          }
          if (item.children) {
            item.children = removeItemById(id, item.children);
          }
          return true; // Keep the item
        });
      };
      return removeItemById(itemId, prevlayout);
    });
  };

  const addItemToModel = (newItem, gridId) => {
    if (gridId === "master") {
      setLayout((prevLayout) => [...prevLayout, newItem]);
    } else {
      setLayout((prevLayout) => {
        const getNewLayout = (layout, newItem) => {
          return layout.map((item) => {
            if ("children" in item && String(gridId) === String(item.id)) {
              return {
                ...item,
                children: [...item.children, newItem],
              };
            } else if ("children" in item) {
              return {
                ...item,
                children: getNewLayout(item.children, newItem),
              };
            } else {
              return item;
            }
          });
        };
        return getNewLayout(prevLayout, newItem);
      });
    }
  };

  const [areChildrenMounted, setAreChildrenMounted] = useState(false);

  const attachEventListeners = () => {
    grid.current.on("added change", (event, items) => {
      for (let item of items) {
        const { x, y, w, h, el } = item;
        if (!("id" in item)) {
          // The item has been dragged and dropped from outside!
          const { dnd } = props;
          const { dndItems } = dnd;
          if ("uidGenerator" in dnd) {
            const dndItemId = el.getAttribute("gs-dnd-item-id");
            const dndItem = cloneDeep(
              dndItems.find(
                (dndItem) => String(dndItem.id) === String(dndItemId)
              )
            );
            if (dndItem) {
              Object.assign(dndItem, {
                x,
                y,
                w,
                h,
                id: String(dnd.uidGenerator()),
              });
              addItemToModel(dndItem, "master"); // Push item to the layout.
              itemsHash.current[dndItem.id] = dndItem;
            }
            grid.current.removeWidget(item.el, true);
          } else {
            throw new Error(
              "Fatal error: Please supply a UID generator to the grid to support drag and drop of items which doesn't belong to any gridstack grid."
            );
          }
        } else if (itemsHash.current[item.id]) {
          // The item is part of this grid only...
          Object.assign(itemsHash.current[item.id], { w, h, x, y });
          updateLayout(item);
        } else if (itemStore.isPresent(item.id)) {
          // The grid item is coming from another grid. User has dragged and dropped an item belonging to another grid.
          const retrievedItem = itemStore.retrieve();
          Object.assign(retrievedItem, { x, y, w, h });
          itemStore.clear();
          itemsHash.current[retrievedItem.id] = retrievedItem;
          addItemToModel(retrievedItem, "master"); // Push item to the layout.
          // Add the retrieved item to this grid, since it was dropped on this particular grid!
        } else {
          throw new Error("Item not present in the current grid!");
        }
      }
    });

    grid.current.on("removed", (event, items) => {
      // Don't update the model if the grid is destoryed.
      if (!isGridDestroyed.current) {
        for (let item of items) {
          // Dnd items dont' have id, they have _id!
          if ("id" in item) {
            if ("_temporaryRemoved" in item) {
              // This particular item is removed from a grid, and will be added to another grid... This happens when the user drags and drop a
              // grid item from one grid to another.
              const itemToStore = itemsHash.current[item.id];
              if (itemToStore) {
                itemStore.store(itemToStore);
              } else {
                throw new Error(
                  "Item `_temporaryRemoved` from a grid, but the item is not even present in that particular grid!"
                );
              }
            }
            delete itemsHash.current[item.id];
            removeItemFromModel(item.id);
          }
        }
      }
    });
  };

  const updateLayout = (item) => {
    if (item) {
      setLayout((prevLayout) => {
        return getUpdatedLayout(prevLayout, item);
      });
    } else {
      throw new Error("No item supplied, how do I update the layout?");
    }
  };

  const store = useRef();
  const itemStore = {
    isPresent: function (id) {
      return store.current?.id === id;
    },
    store: function (item) {
      store.current = cloneDeep(item);
    },
    retrieve: function () {
      if (store.current) {
        return store.current;
      } else {
        throw new Error("Can't retrive item from an empty itemStore!");
      }
    },
    clear: function () {
      store.current = null;
      console.log("store cleared, data stored in store = ", store);
    },
  };

  useEffect(() => {
    if (!areChildrenMounted) {
      const { accept = [], dnd } = props;

      const getDndOptions = () => {
        const { dnd } = props;
        const { options, shredder } = dnd ?? {};
        if (dnd?.class) {
          const gridstackDragAndDropOptions = {
            dragIn: dnd.class,
          };
          if (options) {
            gridstackDragAndDropOptions["dragInOptions"] = options;
          }
          if (shredder) {
            gridstackDragAndDropOptions["removable"] = shredder;
          }
          return gridstackDragAndDropOptions;
        } else {
          return {};
        }
      };

      grid.current = GridStack.init(
        {
          ...masterGridOptions,
          ...getDndOptions(),
          acceptWidgets: (el) => {
            const classList = new Set(el.classList);
            for (let i = 0; i < accept.length; i++) {
              if (classList.has(accept[i]) || classList.has(dnd?.class ?? "")) {
                return true;
              }
            }
            return false;
          },
        },
        gridContainerElement.current
      );
      isGridDestroyed.current = false;
      attachEventListeners();
      setAreChildrenMounted(true);
    } else {
      throw new Error(
        "Fatal error: Must not initialize Gridstack instance multiple times."
      );
    }
    return () => {
      if (!isGridDestroyed.current) {
        isGridDestroyed.current = true;
        grid.current.destroy(false); // Destroy grid but don't remove all the DOM nodes... React will do that for you.
      } else {
        throw new Error(
          "Fatal error: Trying to destory a grid that has already been destroyed."
        );
      }
    };
    // eslint-disable-next-line
  }, []);

  const { setLayout, children } = props;
  return (
    <MasterGridContext.Provider value={grid.current}>
      <UpdateLayoutContext.Provider value={updateLayout}>
        <RemoveItemFromModelContext.Provider value={removeItemFromModel}>
          <AddItemToModelContext.Provider value={addItemToModel}>
            <ItemStoreContext.Provider value={itemStore}>
              <div className="grid-stack" ref={gridContainerElement}>
                {areChildrenMounted ? children : null}
              </div>
            </ItemStoreContext.Provider>
          </AddItemToModelContext.Provider>
        </RemoveItemFromModelContext.Provider>
      </UpdateLayoutContext.Provider>
    </MasterGridContext.Provider>
  );
});

export default GridstackLayout;

// packages/vue/src/gridstack/GridstackContainer.vue
<template>
  <div class="grid-stack"><slot></slot></div>
</template>
<script>
import { GridStack } from "@declarative-gridstack/core";
import { cloneDeep, isEmpty } from "lodash";
import "@declarative-gridstack/core/dist/gridstack-extra.min.css";
import "@declarative-gridstack/core/dist/gridstack.min.css";
export default {
  name: "GridstackLayout",
  data() {
    return {
      masterGrid: null,
      storedItem: null,
    };
  },
  props: {
    margin: {
      type: [String, Number],
      default: 10,
    },
    columns: {
      type: [String, Number],
      default: 12,
      validator: (value) => Number(value) >= 1 && Number(value) <= 12, // Handles max. 12 columns for now.
    },
    dnd: {
      type: Object,
      validator: (obj) =>
        obj?.class &&
        typeof obj.class === "string" &&
        "uidGenerator" in obj &&
        typeof obj.uidGenerator === "function",
    },
    minRow: {
      type: Number,
      validator: (value) => value >= 0 && Number.isInteger(value),
      default: 0,
    },
    layout: {
      type: Array,
      required: true,
    },
    accept: {
      type: Array,
      default: () => [],
    },
    rowHeight: {
      type: [Number, String], // 'auto' | 'initial'
      default: 10, // '10px', 1 row size..
    },
    singleColumnMode: {
      type: Boolean,
      default: false,
    },
    singleColumnModeMinW: {
      type: Number,
      default: 100, // 100px
    },
  },
  provide() {
    return {
      saveLayout: this.saveLayout,
      getMasterGridOptions: () => cloneDeep(this.gridOptions),
      storeItem: (item) => {
        if (isEmpty(this.storedItem)) {
          this.storedItem = cloneDeep(item);
          this.$nextTick(() => {
            this.storedItem = null;
          });
        } else {
          throw new Error(
            `Unable to store item '${item.id}', since the store is already occupied by the item ${this.storedItem}.`
          );
        }
      },
      getStoredItem: () => cloneDeep(this.storedItem),
    };
  },
  created() {
    console.log("Gridstacklayout created = ", this._uid);
    const self = this;
    this.$nextTick(() => {
      // init() should be executed after the template has been loaded...
      const getDndOptions = () => {
        const { options, shredder } = self.dnd ?? {};
        if (self.dnd?.class) {
          const dnd = {
            dragIn: self.dnd.class,
          };
          if (options) {
            dnd["dragInOptions"] = options;
          }
          if (shredder) {
            dnd["removable"] = shredder;
          }
          return dnd;
        } else {
          return {};
        }
      };
      self.masterGrid = GridStack.init(
        {
          ...self.gridOptions,
          ...getDndOptions(),
          acceptWidgets: (el) => {
            const classList = new Set(el.classList);
            for (let i = 0; i < self.accept.length; i++) {
              const accept = self.accept[i];
              if (
                classList.has(accept) ||
                classList.has(self.dnd?.class ?? "")
              ) {
                return true;
              }
            }
            return false;
          },
        },
        self.$el
      );
      self.attachEventListeners();
    });
  },
  mounted() {
    console.log("Gridstacklayout mounted = ", this._uid);
    // When 'init' is called no Gridstack items should be present in the layout... If they are present then they would get registered to the Gridstack layout
    // in the init() call itself, we want to manually register the Gridstack items to the layout from within the item itself.
  },
  computed: {
    dndItems() {
      return (this.dnd?.dndItems ?? []).reduce((hash, dndItem) => {
        hash[dndItem.id] = dndItem;
        return hash;
      }, {});
    },
    gridOptions() {
      // Write all the options that will be
      // shared by both gridstack-subgrid and gridstack-container.
      return {
        margin: this.margin,
        disableOneColumnMode: !this.singleColumnMode,
        oneColumnSize: this.singleColumnModeMinW,
        cellHeight: this.rowHeight,
        minRow: this.minRow,
        column: this.columns,
      };
    },
    layoutHash() {
      console.log("Recomputing hash -> ");
      const layoutHash = this.layout.reduce((hashMap, item) => {
        hashMap[item.id] = item;
        return hashMap;
      }, {});
      return layoutHash;
    },
  },
  methods: {
    getMargin() {
      return this.masterGrid.getMargin();
    },
    getRowHeight() {
      return this.masterGrid.getCellHeight();
    },
    updateNumberOfColumns(num, mode = "moveScale") {
      // Supported modes, 'moveScale' | 'move' | 'scale' | 'none'
      this.masterGrid.column(num, mode);
    },
    getItemElementUsingId(id) {
      return this.$el.querySelector(`.grid-stack-item[gs-id="${id}"]`);
    },
    updateItem(item) {
      const el = this.getItemElementUsingId(item.id);
      this.masterGrid.update(el, item);
    },
    saveLayout() {
      this.$emit("layoutChanged");
    },
    removeItemFromModel(id) {
      const index = this.layout.findIndex((item) => item.id == id);
      if (index >= 0) {
        // 'splice' is a mutating method, yes, I am mutating a prop.
        // eslint-disable-next-line vue/no-mutating-props
        this.layout.splice(index, 1);
      } else {
        throw new Error(
          `Error while removing an item from the grid layout.
           The widget with id '${id} doesn't exist in grid layout.`
        );
      }
    },
    removeItem(id) {
      console.log(id);
      // Removes item from 'view'.
      console.log("item to be removed -> ", id);
      const item = this.getItemElementUsingId(id);
      this.masterGrid.removeWidget(item, false); // RemoveDOM = false, don't remove DOM.
    },
    updateLayout(newLayout) {
      this.$emit("layoutUpdate", newLayout);
    },
    isDndItem(item) {
      return item?.el?.hasAttribute("gs-dnd-item-id") && !("id" in item);
    },
    attachEventListeners() {
      const self = this;
      this.masterGrid.on("change added", (event, items) => {
        // console.log("master grid, added / changed => ", items);
        for (const item of items) {
          const { id, w, h, x, y } = item;
          // Yes, I am low key mutating a prop.
          if (self.layoutHash[id]) {
            Object.assign(self.layoutHash[id], { w, h, x, y });
          } else if (self.isDndItem(item)) {
            // Remove the item as soon as it is added.
            // Then layout.push() the item, which will
            // register the item to the model + update the view.
            self.masterGrid.removeWidget(item.el, true);
            const classList = new Set(item?.el.classList);
            if (classList.has(self?.dnd?.class)) {
              // dnd items don't have an id,
              // the id should be generated and assigned by the uidGenerate,
              // which is a callback function provided by the user.
              const dndItemId = item?.el?.getAttribute("gs-dnd-item-id");
              if (dndItemId in self.dndItems) {
                const dndItem = cloneDeep(self.dndItems[dndItemId]);
                Object.assign(dndItem, {
                  x,
                  y,
                  w,
                  h,
                  id: self.dnd?.uidGenerator(),
                });
                // eslint-disable-next-line vue/no-mutating-props
                self.layout.push(dndItem);
              } else {
                throw new Error(
                  `The dnd item that you dropped into this grid cannot be found
                   in the dndItems you supplied... Please include this item in dndItems
                   of the dnd prop that you have supplied to this grid.`
                );
              }
            } else {
              throw new Error(
                `This grid doesn't accept the dnd item that you have dropped into it now.
                 This grid only accepts dnd items having class ${self.dnd?.class}!
                 `
              );
            }
          }
          // else if (false) {

          //   // TODO: Check if an item from any subgrid has been moved into the mastergrid.
          // }
          else {
            throw new Error(
              `We are attempting to apply the '${event.type}' event to a widget that
               does not exist in this grid layout.`
            );
          }
        }
        self.saveLayout();
      });
      this.masterGrid.on("removed", (event, items) => {
        for (const item of items) {
          if (!self.isDndItem(item)) {
            // The item was never added to the model,
            // no point in remove it from the model...
            this.removeItemFromModel(item.id);
          }
        }
        this.saveLayout();
      });
    },
    detachEventListeners() {},
  },
};
</script>

<style lang="scss">
.grid-stack {
  border: 1px solid red;
}
</style>
